# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newSim.ui'
#
# Created: Thu Jan 21 10:33:39 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_simulation_Frame(object):
    def setupUi(self, simulation_Frame):
        simulation_Frame.setObjectName(_fromUtf8("simulation_Frame"))
        simulation_Frame.setWindowModality(QtCore.Qt.WindowModal)
        simulation_Frame.resize(640, 900)
        simulation_Frame.setMinimumSize(QtCore.QSize(640, 900))
        simulation_Frame.setMaximumSize(QtCore.QSize(640, 900))
        self.line = QtGui.QFrame(simulation_Frame)
        self.line.setGeometry(QtCore.QRect(0, 50, 641, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(simulation_Frame)
        self.line_2.setGeometry(QtCore.QRect(0, 190, 641, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(simulation_Frame)
        self.line_3.setGeometry(QtCore.QRect(0, 230, 641, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(simulation_Frame)
        self.line_4.setGeometry(QtCore.QRect(0, 510, 641, 20))
        self.line_4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(simulation_Frame)
        self.line_5.setGeometry(QtCore.QRect(0, 560, 641, 20))
        self.line_5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(simulation_Frame)
        self.line_6.setGeometry(QtCore.QRect(0, 840, 641, 20))
        self.line_6.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label = QtGui.QLabel(simulation_Frame)
        self.label.setGeometry(QtCore.QRect(20, 40, 173, 31))
        self.label.setAutoFillBackground(True)
        self.label.setFrameShape(QtGui.QFrame.Box)
        self.label.setFrameShadow(QtGui.QFrame.Raised)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(simulation_Frame)
        self.label_2.setGeometry(QtCore.QRect(20, 220, 173, 31))
        self.label_2.setAutoFillBackground(True)
        self.label_2.setFrameShape(QtGui.QFrame.Box)
        self.label_2.setFrameShadow(QtGui.QFrame.Raised)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(simulation_Frame)
        self.label_3.setGeometry(QtCore.QRect(20, 550, 173, 31))
        self.label_3.setAutoFillBackground(True)
        self.label_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_3.setFrameShape(QtGui.QFrame.Box)
        self.label_3.setFrameShadow(QtGui.QFrame.Raised)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(simulation_Frame)
        self.label_4.setGeometry(QtCore.QRect(90, 90, 171, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.Seed_checkBox = QtGui.QCheckBox(simulation_Frame)
        self.Seed_checkBox.setGeometry(QtCore.QRect(90, 140, 171, 31))
        self.Seed_checkBox.setObjectName(_fromUtf8("Seed_checkBox"))
        self.Sim_textCtl = QtGui.QLineEdit(simulation_Frame)
        self.Sim_textCtl.setGeometry(QtCore.QRect(280, 90, 100, 31))
        self.Sim_textCtl.setObjectName(_fromUtf8("Sim_textCtl"))
        self.Seed_textCtl = QtGui.QLineEdit(simulation_Frame)
        self.Seed_textCtl.setEnabled(False)
        self.Seed_textCtl.setGeometry(QtCore.QRect(280, 140, 100, 31))
        self.Seed_textCtl.setObjectName(_fromUtf8("Seed_textCtl"))
        self.label_5 = QtGui.QLabel(simulation_Frame)
        self.label_5.setGeometry(QtCore.QRect(400, 90, 171, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(simulation_Frame)
        self.label_6.setGeometry(QtCore.QRect(400, 140, 171, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(simulation_Frame)
        self.label_7.setGeometry(QtCore.QRect(40, 270, 171, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(simulation_Frame)
        self.label_8.setGeometry(QtCore.QRect(40, 320, 171, 31))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(simulation_Frame)
        self.label_9.setGeometry(QtCore.QRect(40, 370, 171, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(simulation_Frame)
        self.label_10.setGeometry(QtCore.QRect(40, 420, 171, 31))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(simulation_Frame)
        self.label_11.setGeometry(QtCore.QRect(40, 470, 241, 31))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.Ful_textCtl = QtGui.QLineEdit(simulation_Frame)
        self.Ful_textCtl.setGeometry(QtCore.QRect(210, 370, 101, 31))
        self.Ful_textCtl.setUpdatesEnabled(True)
        self.Ful_textCtl.setVisible(True)
        self.Ful_textCtl.setWindowTitle(_fromUtf8(""))
        self.Ful_textCtl.setWindowIconText(_fromUtf8(""))
        self.Ful_textCtl.setWindowOpacity(1.0)
        self.Ful_textCtl.setWindowModified(False)
        self.Ful_textCtl.setWindowFilePath(_fromUtf8(""))
        self.Ful_textCtl.setModified(False)
        self.Ful_textCtl.setObjectName(_fromUtf8("Ful_textCtl"))
        self.nArm_comboBox = QtGui.QComboBox(simulation_Frame)
        self.nArm_comboBox.setGeometry(QtCore.QRect(210, 270, 101, 31))
        self.nArm_comboBox.setUpdatesEnabled(True)
        self.nArm_comboBox.setVisible(True)
        self.nArm_comboBox.setWindowTitle(_fromUtf8(""))
        self.nArm_comboBox.setWindowIconText(_fromUtf8(""))
        self.nArm_comboBox.setWindowOpacity(1.0)
        self.nArm_comboBox.setWindowModified(False)
        self.nArm_comboBox.setWindowFilePath(_fromUtf8(""))
        self.nArm_comboBox.setAutoCompletion(True)
        self.nArm_comboBox.setAutoCompletionCaseSensitivity(QtCore.Qt.CaseInsensitive)
        self.nArm_comboBox.setObjectName(_fromUtf8("nArm_comboBox"))
        self.nArm_comboBox.addItem(_fromUtf8(""))
        self.nArm_comboBox.addItem(_fromUtf8(""))
        self.nArm_comboBox.addItem(_fromUtf8(""))
        self.nArm_comboBox.addItem(_fromUtf8(""))
        self.nArm_comboBox.addItem(_fromUtf8(""))
        self.nStage_comboBox = QtGui.QComboBox(simulation_Frame)
        self.nStage_comboBox.setGeometry(QtCore.QRect(210, 320, 101, 31))
        self.nStage_comboBox.setUpdatesEnabled(True)
        self.nStage_comboBox.setVisible(True)
        self.nStage_comboBox.setWindowTitle(_fromUtf8(""))
        self.nStage_comboBox.setWindowIconText(_fromUtf8(""))
        self.nStage_comboBox.setWindowOpacity(1.0)
        self.nStage_comboBox.setWindowModified(False)
        self.nStage_comboBox.setWindowFilePath(_fromUtf8(""))
        self.nStage_comboBox.setAutoCompletion(True)
        self.nStage_comboBox.setAutoCompletionCaseSensitivity(QtCore.Qt.CaseInsensitive)
        self.nStage_comboBox.setObjectName(_fromUtf8("nStage_comboBox"))
        self.nStage_comboBox.addItem(_fromUtf8(""))
        self.nStage_comboBox.addItem(_fromUtf8(""))
        self.nStage_comboBox.addItem(_fromUtf8(""))
        self.nStage_comboBox.addItem(_fromUtf8(""))
        self.Eff_textCtl = QtGui.QLineEdit(simulation_Frame)
        self.Eff_textCtl.setGeometry(QtCore.QRect(210, 420, 101, 31))
        self.Eff_textCtl.setUpdatesEnabled(True)
        self.Eff_textCtl.setVisible(True)
        self.Eff_textCtl.setWindowTitle(_fromUtf8(""))
        self.Eff_textCtl.setWindowIconText(_fromUtf8(""))
        self.Eff_textCtl.setWindowOpacity(1.0)
        self.Eff_textCtl.setWindowModified(False)
        self.Eff_textCtl.setWindowFilePath(_fromUtf8(""))
        self.Eff_textCtl.setModified(False)
        self.Eff_textCtl.setObjectName(_fromUtf8("Eff_textCtl"))
        self.ClinSig_textCtl = QtGui.QLineEdit(simulation_Frame)
        self.ClinSig_textCtl.setGeometry(QtCore.QRect(300, 470, 101, 31))
        self.ClinSig_textCtl.setUpdatesEnabled(True)
        self.ClinSig_textCtl.setVisible(True)
        self.ClinSig_textCtl.setWindowTitle(_fromUtf8(""))
        self.ClinSig_textCtl.setWindowIconText(_fromUtf8(""))
        self.ClinSig_textCtl.setWindowOpacity(1.0)
        self.ClinSig_textCtl.setWindowModified(False)
        self.ClinSig_textCtl.setWindowFilePath(_fromUtf8(""))
        self.ClinSig_textCtl.setModified(False)
        self.ClinSig_textCtl.setObjectName(_fromUtf8("ClinSig_textCtl"))
        self.assignEffectiveSize_btn = QtGui.QPushButton(simulation_Frame)
        self.assignEffectiveSize_btn.setEnabled(False)
        self.assignEffectiveSize_btn.setGeometry(QtCore.QRect(340, 270, 261, 34))
        self.assignEffectiveSize_btn.setUpdatesEnabled(True)
        self.assignEffectiveSize_btn.setVisible(True)
        self.assignEffectiveSize_btn.setWindowTitle(_fromUtf8(""))
        self.assignEffectiveSize_btn.setWindowIconText(_fromUtf8(""))
        self.assignEffectiveSize_btn.setWindowOpacity(1.0)
        self.assignEffectiveSize_btn.setWindowModified(False)
        self.assignEffectiveSize_btn.setWindowFilePath(_fromUtf8(""))
        self.assignEffectiveSize_btn.setChecked(False)
        self.assignEffectiveSize_btn.setDown(False)
        self.assignEffectiveSize_btn.setObjectName(_fromUtf8("assignEffectiveSize_btn"))
        self.assignPatient_btn = QtGui.QPushButton(simulation_Frame)
        self.assignPatient_btn.setEnabled(False)
        self.assignPatient_btn.setGeometry(QtCore.QRect(340, 320, 261, 34))
        self.assignPatient_btn.setUpdatesEnabled(True)
        self.assignPatient_btn.setVisible(True)
        self.assignPatient_btn.setWindowTitle(_fromUtf8(""))
        self.assignPatient_btn.setWindowIconText(_fromUtf8(""))
        self.assignPatient_btn.setWindowOpacity(1.0)
        self.assignPatient_btn.setWindowModified(False)
        self.assignPatient_btn.setWindowFilePath(_fromUtf8(""))
        self.assignPatient_btn.setChecked(False)
        self.assignPatient_btn.setDown(False)
        self.assignPatient_btn.setObjectName(_fromUtf8("assignPatient_btn"))
        self.predProb_checkBox = QtGui.QCheckBox(simulation_Frame)
        self.predProb_checkBox.setGeometry(QtCore.QRect(40, 610, 261, 23))
        self.predProb_checkBox.setUpdatesEnabled(True)
        self.predProb_checkBox.setVisible(True)
        self.predProb_checkBox.setWindowTitle(_fromUtf8(""))
        self.predProb_checkBox.setWindowIconText(_fromUtf8(""))
        self.predProb_checkBox.setWindowOpacity(1.0)
        self.predProb_checkBox.setWindowModified(False)
        self.predProb_checkBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.predProb_checkBox.setWindowFilePath(_fromUtf8(""))
        self.predProb_checkBox.setDown(False)
        self.predProb_checkBox.setObjectName(_fromUtf8("predProb_checkBox"))
        self.loadCVL_textCtl = QtGui.QLineEdit(simulation_Frame)
        self.loadCVL_textCtl.setEnabled(False)
        self.loadCVL_textCtl.setGeometry(QtCore.QRect(320, 750, 251, 31))
        self.loadCVL_textCtl.setUpdatesEnabled(True)
        self.loadCVL_textCtl.setVisible(True)
        self.loadCVL_textCtl.setWindowTitle(_fromUtf8(""))
        self.loadCVL_textCtl.setWindowIconText(_fromUtf8(""))
        self.loadCVL_textCtl.setWindowOpacity(1.0)
        self.loadCVL_textCtl.setWindowModified(False)
        self.loadCVL_textCtl.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.loadCVL_textCtl.setWindowFilePath(_fromUtf8(""))
        self.loadCVL_textCtl.setModified(False)
        self.loadCVL_textCtl.setObjectName(_fromUtf8("loadCVL_textCtl"))
        self.predSuccess_textCtl = QtGui.QLineEdit(simulation_Frame)
        self.predSuccess_textCtl.setEnabled(False)
        self.predSuccess_textCtl.setGeometry(QtCore.QRect(280, 700, 101, 31))
        self.predSuccess_textCtl.setUpdatesEnabled(True)
        self.predSuccess_textCtl.setVisible(True)
        self.predSuccess_textCtl.setWindowTitle(_fromUtf8(""))
        self.predSuccess_textCtl.setWindowIconText(_fromUtf8(""))
        self.predSuccess_textCtl.setWindowOpacity(1.0)
        self.predSuccess_textCtl.setWindowModified(False)
        self.predSuccess_textCtl.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.predSuccess_textCtl.setWindowFilePath(_fromUtf8(""))
        self.predSuccess_textCtl.setModified(False)
        self.predSuccess_textCtl.setObjectName(_fromUtf8("predSuccess_textCtl"))
        self.loadCVL_btn = QtGui.QPushButton(simulation_Frame)
        self.loadCVL_btn.setEnabled(False)
        self.loadCVL_btn.setGeometry(QtCore.QRect(590, 750, 41, 34))
        self.loadCVL_btn.setUpdatesEnabled(True)
        self.loadCVL_btn.setVisible(True)
        self.loadCVL_btn.setWindowTitle(_fromUtf8(""))
        self.loadCVL_btn.setWindowIconText(_fromUtf8(""))
        self.loadCVL_btn.setWindowOpacity(1.0)
        self.loadCVL_btn.setWindowModified(False)
        self.loadCVL_btn.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.loadCVL_btn.setWindowFilePath(_fromUtf8(""))
        self.loadCVL_btn.setChecked(False)
        self.loadCVL_btn.setDown(False)
        self.loadCVL_btn.setObjectName(_fromUtf8("loadCVL_btn"))
        self.predNum_textCtl = QtGui.QLineEdit(simulation_Frame)
        self.predNum_textCtl.setEnabled(False)
        self.predNum_textCtl.setGeometry(QtCore.QRect(280, 650, 101, 31))
        self.predNum_textCtl.setUpdatesEnabled(True)
        self.predNum_textCtl.setVisible(True)
        self.predNum_textCtl.setWindowTitle(_fromUtf8(""))
        self.predNum_textCtl.setWindowIconText(_fromUtf8(""))
        self.predNum_textCtl.setWindowOpacity(1.0)
        self.predNum_textCtl.setWindowModified(False)
        self.predNum_textCtl.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.predNum_textCtl.setWindowFilePath(_fromUtf8(""))
        self.predNum_textCtl.setModified(False)
        self.predNum_textCtl.setObjectName(_fromUtf8("predNum_textCtl"))
        self.loadCVL_checkBox = QtGui.QCheckBox(simulation_Frame)
        self.loadCVL_checkBox.setEnabled(False)
        self.loadCVL_checkBox.setGeometry(QtCore.QRect(40, 750, 301, 23))
        self.loadCVL_checkBox.setUpdatesEnabled(True)
        self.loadCVL_checkBox.setVisible(True)
        self.loadCVL_checkBox.setWindowTitle(_fromUtf8(""))
        self.loadCVL_checkBox.setWindowIconText(_fromUtf8(""))
        self.loadCVL_checkBox.setWindowOpacity(1.0)
        self.loadCVL_checkBox.setWindowModified(False)
        self.loadCVL_checkBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.loadCVL_checkBox.setWindowFilePath(_fromUtf8(""))
        self.loadCVL_checkBox.setDown(False)
        self.loadCVL_checkBox.setObjectName(_fromUtf8("loadCVL_checkBox"))
        self.label_14 = QtGui.QLabel(simulation_Frame)
        self.label_14.setGeometry(QtCore.QRect(40, 640, 221, 31))
        self.label_14.setUpdatesEnabled(True)
        self.label_14.setVisible(True)
        self.label_14.setWindowTitle(_fromUtf8(""))
        self.label_14.setWindowIconText(_fromUtf8(""))
        self.label_14.setWindowOpacity(1.0)
        self.label_14.setWindowModified(False)
        self.label_14.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_14.setWindowFilePath(_fromUtf8(""))
        self.label_14.setFrameRect(QtCore.QRect(0, 0, 385, 43))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(simulation_Frame)
        self.label_15.setGeometry(QtCore.QRect(40, 690, 231, 31))
        self.label_15.setUpdatesEnabled(True)
        self.label_15.setVisible(True)
        self.label_15.setWindowTitle(_fromUtf8(""))
        self.label_15.setWindowIconText(_fromUtf8(""))
        self.label_15.setWindowOpacity(1.0)
        self.label_15.setWindowModified(False)
        self.label_15.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_15.setWindowFilePath(_fromUtf8(""))
        self.label_15.setFrameRect(QtCore.QRect(0, 0, 395, 43))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.runSim_btn = QtGui.QPushButton(simulation_Frame)
        self.runSim_btn.setGeometry(QtCore.QRect(380, 860, 112, 34))
        self.runSim_btn.setUpdatesEnabled(True)
        self.runSim_btn.setVisible(True)
        self.runSim_btn.setWindowTitle(_fromUtf8(""))
        self.runSim_btn.setWindowIconText(_fromUtf8(""))
        self.runSim_btn.setWindowOpacity(1.0)
        self.runSim_btn.setWindowModified(False)
        self.runSim_btn.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.runSim_btn.setWindowFilePath(_fromUtf8(""))
        self.runSim_btn.setChecked(False)
        self.runSim_btn.setDown(False)
        self.runSim_btn.setObjectName(_fromUtf8("runSim_btn"))
        self.cancelSim_btn = QtGui.QPushButton(simulation_Frame)
        self.cancelSim_btn.setGeometry(QtCore.QRect(510, 860, 112, 34))
        self.cancelSim_btn.setUpdatesEnabled(True)
        self.cancelSim_btn.setVisible(True)
        self.cancelSim_btn.setWindowTitle(_fromUtf8(""))
        self.cancelSim_btn.setWindowIconText(_fromUtf8(""))
        self.cancelSim_btn.setWindowOpacity(1.0)
        self.cancelSim_btn.setWindowModified(False)
        self.cancelSim_btn.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cancelSim_btn.setWindowFilePath(_fromUtf8(""))
        self.cancelSim_btn.setChecked(False)
        self.cancelSim_btn.setDown(False)
        self.cancelSim_btn.setObjectName(_fromUtf8("cancelSim_btn"))
        self.saveCVL_textCtl = QtGui.QLineEdit(simulation_Frame)
        self.saveCVL_textCtl.setEnabled(False)
        self.saveCVL_textCtl.setGeometry(QtCore.QRect(320, 800, 251, 31))
        self.saveCVL_textCtl.setUpdatesEnabled(True)
        self.saveCVL_textCtl.setVisible(True)
        self.saveCVL_textCtl.setWindowTitle(_fromUtf8(""))
        self.saveCVL_textCtl.setWindowIconText(_fromUtf8(""))
        self.saveCVL_textCtl.setWindowOpacity(1.0)
        self.saveCVL_textCtl.setWindowModified(False)
        self.saveCVL_textCtl.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.saveCVL_textCtl.setWindowFilePath(_fromUtf8(""))
        self.saveCVL_textCtl.setModified(False)
        self.saveCVL_textCtl.setObjectName(_fromUtf8("saveCVL_textCtl"))
        self.saveCVL_checkBox = QtGui.QCheckBox(simulation_Frame)
        self.saveCVL_checkBox.setEnabled(False)
        self.saveCVL_checkBox.setGeometry(QtCore.QRect(40, 800, 301, 23))
        self.saveCVL_checkBox.setUpdatesEnabled(True)
        self.saveCVL_checkBox.setVisible(True)
        self.saveCVL_checkBox.setWindowTitle(_fromUtf8(""))
        self.saveCVL_checkBox.setWindowIconText(_fromUtf8(""))
        self.saveCVL_checkBox.setWindowOpacity(1.0)
        self.saveCVL_checkBox.setWindowModified(False)
        self.saveCVL_checkBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.saveCVL_checkBox.setWindowFilePath(_fromUtf8(""))
        self.saveCVL_checkBox.setDown(False)
        self.saveCVL_checkBox.setObjectName(_fromUtf8("saveCVL_checkBox"))
        self.saveCVL_btn = QtGui.QPushButton(simulation_Frame)
        self.saveCVL_btn.setEnabled(False)
        self.saveCVL_btn.setGeometry(QtCore.QRect(590, 800, 41, 34))
        self.saveCVL_btn.setUpdatesEnabled(True)
        self.saveCVL_btn.setVisible(True)
        self.saveCVL_btn.setWindowTitle(_fromUtf8(""))
        self.saveCVL_btn.setWindowIconText(_fromUtf8(""))
        self.saveCVL_btn.setWindowOpacity(1.0)
        self.saveCVL_btn.setWindowModified(False)
        self.saveCVL_btn.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.saveCVL_btn.setWindowFilePath(_fromUtf8(""))
        self.saveCVL_btn.setChecked(False)
        self.saveCVL_btn.setDown(False)
        self.saveCVL_btn.setObjectName(_fromUtf8("saveCVL_btn"))

        self.retranslateUi(simulation_Frame)
        self.nArm_comboBox.setCurrentIndex(-1)
        self.nStage_comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(simulation_Frame)
        simulation_Frame.setTabOrder(self.Sim_textCtl, self.Seed_checkBox)
        simulation_Frame.setTabOrder(self.Seed_checkBox, self.Seed_textCtl)
        simulation_Frame.setTabOrder(self.Seed_textCtl, self.nArm_comboBox)
        simulation_Frame.setTabOrder(self.nArm_comboBox, self.assignEffectiveSize_btn)
        simulation_Frame.setTabOrder(self.assignEffectiveSize_btn, self.nStage_comboBox)
        simulation_Frame.setTabOrder(self.nStage_comboBox, self.assignPatient_btn)
        simulation_Frame.setTabOrder(self.assignPatient_btn, self.Ful_textCtl)
        simulation_Frame.setTabOrder(self.Ful_textCtl, self.Eff_textCtl)
        simulation_Frame.setTabOrder(self.Eff_textCtl, self.ClinSig_textCtl)
        simulation_Frame.setTabOrder(self.ClinSig_textCtl, self.predProb_checkBox)
        simulation_Frame.setTabOrder(self.predProb_checkBox, self.predNum_textCtl)
        simulation_Frame.setTabOrder(self.predNum_textCtl, self.predSuccess_textCtl)
        simulation_Frame.setTabOrder(self.predSuccess_textCtl, self.loadCVL_checkBox)
        simulation_Frame.setTabOrder(self.loadCVL_checkBox, self.loadCVL_textCtl)
        simulation_Frame.setTabOrder(self.loadCVL_textCtl, self.loadCVL_btn)
        simulation_Frame.setTabOrder(self.loadCVL_btn, self.runSim_btn)
        simulation_Frame.setTabOrder(self.runSim_btn, self.cancelSim_btn)

    def retranslateUi(self, simulation_Frame):
        simulation_Frame.setWindowTitle(_translate("simulation_Frame", "New Trial Simulation", None))
        self.label.setText(_translate("simulation_Frame", "Simulation Setting", None))
        self.label_2.setText(_translate("simulation_Frame", "Trial Setting", None))
        self.label_3.setText(_translate("simulation_Frame", "Predictive Probability", None))
        self.label_4.setText(_translate("simulation_Frame", "Number of Simulations:", None))
        self.Seed_checkBox.setText(_translate("simulation_Frame", "Simulation Seed:", None))
        self.label_5.setText(_translate("simulation_Frame", "(<100,000)", None))
        self.label_6.setText(_translate("simulation_Frame", "(1~999999)", None))
        self.label_7.setText(_translate("simulation_Frame", "Number of Arms:", None))
        self.label_8.setText(_translate("simulation_Frame", "Number of Stages:", None))
        self.label_9.setText(_translate("simulation_Frame", "Futility Boundary:", None))
        self.label_10.setText(_translate("simulation_Frame", "Efficacy Boundary:", None))
        self.label_11.setText(_translate("simulation_Frame", "Clinically Sigificant Difference:", None))
        self.nArm_comboBox.setItemText(0, _translate("simulation_Frame", "2", None))
        self.nArm_comboBox.setItemText(1, _translate("simulation_Frame", "3", None))
        self.nArm_comboBox.setItemText(2, _translate("simulation_Frame", "4", None))
        self.nArm_comboBox.setItemText(3, _translate("simulation_Frame", "5", None))
        self.nArm_comboBox.setItemText(4, _translate("simulation_Frame", "6", None))
        self.nStage_comboBox.setItemText(0, _translate("simulation_Frame", "2", None))
        self.nStage_comboBox.setItemText(1, _translate("simulation_Frame", "3", None))
        self.nStage_comboBox.setItemText(2, _translate("simulation_Frame", "4", None))
        self.nStage_comboBox.setItemText(3, _translate("simulation_Frame", "5", None))
        self.assignEffectiveSize_btn.setText(_translate("simulation_Frame", "Assign Effective Size for Each Arm", None))
        self.assignPatient_btn.setText(_translate("simulation_Frame", "Assign Patients at Each Stage", None))
        self.predProb_checkBox.setText(_translate("simulation_Frame", "Calculate Predictive Probability", None))
        self.loadCVL_btn.setText(_translate("simulation_Frame", "...", None))
        self.loadCVL_checkBox.setText(_translate("simulation_Frame", "Load Critical Value Lookup Table:", None))
        self.label_14.setText(_translate("simulation_Frame", "Number of Patients Added:", None))
        self.label_15.setText(_translate("simulation_Frame", "Success Boundary:", None))
        self.runSim_btn.setText(_translate("simulation_Frame", "Run", None))
        self.cancelSim_btn.setText(_translate("simulation_Frame", "Cancel", None))
        self.saveCVL_checkBox.setText(_translate("simulation_Frame", "Save Critical Value Lookup Table:", None))
        self.saveCVL_btn.setText(_translate("simulation_Frame", "...", None))

