# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MAMSWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MAMSWindow(object):
    def setupUi(self, MAMSWindow):
        MAMSWindow.setObjectName("MAMSWindow")
        MAMSWindow.resize(800, 732)
        self.verticalLayout = QtWidgets.QVBoxLayout(MAMSWindow)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingArea = QtWidgets.QScrollArea(MAMSWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.settingArea.setFont(font)
        self.settingArea.setFocusPolicy(QtCore.Qt.NoFocus)
        self.settingArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.settingArea.setWidgetResizable(True)
        self.settingArea.setObjectName("settingArea")
        self.settingContent = QtWidgets.QWidget()
        self.settingContent.setGeometry(QtCore.QRect(0, 0, 772, 3153))
        self.settingContent.setObjectName("settingContent")
        self.gridLayout = QtWidgets.QGridLayout(self.settingContent)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.trtEffSize_btn = QtWidgets.QPushButton(self.settingContent)
        self.trtEffSize_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.trtEffSize_btn.setFont(font)
        self.trtEffSize_btn.setObjectName("trtEffSize_btn")
        self.gridLayout.addWidget(self.trtEffSize_btn, 13, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 36, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 13, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 19, 6, 1, 1)
        self.stopBoundary_Frame = QtWidgets.QFrame(self.settingContent)
        self.stopBoundary_Frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.stopBoundary_Frame.setStyleSheet("QFrame#stopBoundary_Frame{\n"
"     border: 1px solid #399ee5;\n"
"     border-radius： 5px;\n"
"     border-left: 3px solid #399ee5;\n"
"}")
        self.stopBoundary_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stopBoundary_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stopBoundary_Frame.setObjectName("stopBoundary_Frame")
        self.formLayout_4 = QtWidgets.QFormLayout(self.stopBoundary_Frame)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_4.setContentsMargins(20, 20, 20, 20)
        self.formLayout_4.setObjectName("formLayout_4")
        self.cancelBoundary_btn = QtWidgets.QToolButton(self.stopBoundary_Frame)
        self.cancelBoundary_btn.setStyleSheet("QToolButton:hover{\n"
"     background: #cce5f3;\n"
"     border: 1px solid #fafbfc;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelBoundary_btn.setIcon(icon)
        self.cancelBoundary_btn.setObjectName("cancelBoundary_btn")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cancelBoundary_btn)
        self.stopBoundary_tableWidget = QtWidgets.QTableWidget(self.stopBoundary_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopBoundary_tableWidget.sizePolicy().hasHeightForWidth())
        self.stopBoundary_tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.stopBoundary_tableWidget.setFont(font)
        self.stopBoundary_tableWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.stopBoundary_tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stopBoundary_tableWidget.setStyleSheet("QLineEdit{\n"
"    min-width: 80px;\n"
"    max-width: 1000px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}\n"
"")
        self.stopBoundary_tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.stopBoundary_tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.stopBoundary_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.stopBoundary_tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.stopBoundary_tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.stopBoundary_tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.stopBoundary_tableWidget.setObjectName("stopBoundary_tableWidget")
        self.stopBoundary_tableWidget.setColumnCount(0)
        self.stopBoundary_tableWidget.setRowCount(0)
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.stopBoundary_tableWidget)
        self.resetBoundary_btn = QtWidgets.QPushButton(self.stopBoundary_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.resetBoundary_btn.setFont(font)
        self.resetBoundary_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetBoundary_btn.setObjectName("resetBoundary_btn")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.resetBoundary_btn)
        self.saveBoundary_btn = QtWidgets.QPushButton(self.stopBoundary_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.saveBoundary_btn.setFont(font)
        self.saveBoundary_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveBoundary_btn.setObjectName("saveBoundary_btn")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.saveBoundary_btn)
        self.gridLayout.addWidget(self.stopBoundary_Frame, 23, 1, 1, 4)
        self.patNum_Frame = QtWidgets.QFrame(self.settingContent)
        self.patNum_Frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.patNum_Frame.setStyleSheet("QFrame#patNum_Frame{\n"
"     border: 1px solid #399ee5;\n"
"     border-radius： 5px;\n"
"     border-left: 3px solid #399ee5;\n"
"}")
        self.patNum_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.patNum_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.patNum_Frame.setObjectName("patNum_Frame")
        self.formLayout = QtWidgets.QFormLayout(self.patNum_Frame)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(20, 20, 20, 20)
        self.formLayout.setObjectName("formLayout")
        self.cancelPat_btn = QtWidgets.QToolButton(self.patNum_Frame)
        self.cancelPat_btn.setStyleSheet("QToolButton:hover{\n"
"     background: #cce5f3;\n"
"     border: 1px solid #fafbfc;\n"
"}\n"
"")
        self.cancelPat_btn.setIcon(icon)
        self.cancelPat_btn.setObjectName("cancelPat_btn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cancelPat_btn)
        self.patNum_tableWidget = QtWidgets.QTableWidget(self.patNum_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patNum_tableWidget.sizePolicy().hasHeightForWidth())
        self.patNum_tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.patNum_tableWidget.setFont(font)
        self.patNum_tableWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.patNum_tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.patNum_tableWidget.setStyleSheet("QLineEdit{\n"
"    min-width: 80px;\n"
"    max-width: 1000px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}\n"
"")
        self.patNum_tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.patNum_tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.patNum_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.patNum_tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.patNum_tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.patNum_tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.patNum_tableWidget.setObjectName("patNum_tableWidget")
        self.patNum_tableWidget.setColumnCount(0)
        self.patNum_tableWidget.setRowCount(0)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.patNum_tableWidget)
        self.resetPat_btn = QtWidgets.QPushButton(self.patNum_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.resetPat_btn.setFont(font)
        self.resetPat_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetPat_btn.setObjectName("resetPat_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.resetPat_btn)
        self.savePat_btn = QtWidgets.QPushButton(self.patNum_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.savePat_btn.setFont(font)
        self.savePat_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.savePat_btn.setObjectName("savePat_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.savePat_btn)
        self.gridLayout.addWidget(self.patNum_Frame, 21, 1, 1, 4)
        self.trtEff_Frame = QtWidgets.QFrame(self.settingContent)
        self.trtEff_Frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.trtEff_Frame.setStyleSheet("QFrame#trtEff_Frame{\n"
"     border: 1px solid #399ee5;\n"
"     border-radius： 5px;\n"
"     border-left: 3px solid #399ee5;\n"
"}")
        self.trtEff_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trtEff_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trtEff_Frame.setObjectName("trtEff_Frame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.trtEff_Frame)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_2.setContentsMargins(20, 20, 20, 20)
        self.formLayout_2.setObjectName("formLayout_2")
        self.effSize_tableWidget = QtWidgets.QTableWidget(self.trtEff_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.effSize_tableWidget.sizePolicy().hasHeightForWidth())
        self.effSize_tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.effSize_tableWidget.setFont(font)
        self.effSize_tableWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.effSize_tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.effSize_tableWidget.setStyleSheet("QLineEdit{\n"
"    min-width: 80px;\n"
"    max-width: 1000px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}")
        self.effSize_tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.effSize_tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.effSize_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.effSize_tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.effSize_tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.effSize_tableWidget.setObjectName("effSize_tableWidget")
        self.effSize_tableWidget.setColumnCount(0)
        self.effSize_tableWidget.setRowCount(0)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.effSize_tableWidget)
        self.cancelEff_btn = QtWidgets.QToolButton(self.trtEff_Frame)
        self.cancelEff_btn.setStyleSheet("QToolButton:hover{\n"
"     background: #cce5f3;\n"
"     border: 1px solid #fafbfc;\n"
"}\n"
"")
        self.cancelEff_btn.setIcon(icon)
        self.cancelEff_btn.setObjectName("cancelEff_btn")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cancelEff_btn)
        self.saveEff_btn = QtWidgets.QPushButton(self.trtEff_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.saveEff_btn.setFont(font)
        self.saveEff_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveEff_btn.setObjectName("saveEff_btn")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.saveEff_btn)
        self.resetEff_btn = QtWidgets.QPushButton(self.trtEff_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.resetEff_btn.setFont(font)
        self.resetEff_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetEff_btn.setObjectName("resetEff_btn")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.resetEff_btn)
        self.gridLayout.addWidget(self.trtEff_Frame, 15, 1, 1, 4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 13, 0, 1, 1)
        self.nStage_Label = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.nStage_Label.setFont(font)
        self.nStage_Label.setObjectName("nStage_Label")
        self.gridLayout.addWidget(self.nStage_Label, 19, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 31, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 29, 0, 1, 1)
        self.predict_checkBox = QtWidgets.QCheckBox(self.settingContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predict_checkBox.sizePolicy().hasHeightForWidth())
        self.predict_checkBox.setSizePolicy(sizePolicy)
        self.predict_checkBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.predict_checkBox.setFont(font)
        self.predict_checkBox.setChecked(False)
        self.predict_checkBox.setObjectName("predict_checkBox")
        self.gridLayout.addWidget(self.predict_checkBox, 29, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.settingContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 5, 0, 1, 1)
        self.sim_Label = QtWidgets.QLabel(self.settingContent)
        self.sim_Label.setMinimumSize(QtCore.QSize(200, 50))
        self.sim_Label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.sim_Label.setFont(font)
        self.sim_Label.setWordWrap(True)
        self.sim_Label.setObjectName("sim_Label")
        self.gridLayout.addWidget(self.sim_Label, 4, 1, 2, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem7, 10, 0, 1, 1)
        self.predNum_Label = QtWidgets.QLabel(self.settingContent)
        self.predNum_Label.setEnabled(False)
        self.predNum_Label.setMinimumSize(QtCore.QSize(0, 0))
        self.predNum_Label.setMaximumSize(QtCore.QSize(16777215, 10000))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.predNum_Label.setFont(font)
        self.predNum_Label.setLineWidth(1)
        self.predNum_Label.setScaledContents(False)
        self.predNum_Label.setWordWrap(True)
        self.predNum_Label.setObjectName("predNum_Label")
        self.gridLayout.addWidget(self.predNum_Label, 31, 1, 1, 1)
        self.clinSig_textCtl = QtWidgets.QLineEdit(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.clinSig_textCtl.setFont(font)
        self.clinSig_textCtl.setUpdatesEnabled(True)
        self.clinSig_textCtl.setVisible(True)
        self.clinSig_textCtl.setWindowTitle("")
        self.clinSig_textCtl.setWindowIconText("")
        self.clinSig_textCtl.setWindowOpacity(1.0)
        self.clinSig_textCtl.setWindowModified(False)
        self.clinSig_textCtl.setWindowFilePath("")
        self.clinSig_textCtl.setModified(False)
        self.clinSig_textCtl.setObjectName("clinSig_textCtl")
        self.gridLayout.addWidget(self.clinSig_textCtl, 27, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 10, 1, 1, 3)
        spacerItem8 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem8, 34, 0, 1, 1)
        self.nArm_comboBox = QtWidgets.QComboBox(self.settingContent)
        self.nArm_comboBox.setMaximumSize(QtCore.QSize(202, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.nArm_comboBox.setFont(font)
        self.nArm_comboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.nArm_comboBox.setStyleSheet("")
        self.nArm_comboBox.setObjectName("nArm_comboBox")
        self.nArm_comboBox.addItem("")
        self.nArm_comboBox.addItem("")
        self.nArm_comboBox.addItem("")
        self.nArm_comboBox.addItem("")
        self.nArm_comboBox.addItem("")
        self.nArm_comboBox.addItem("")
        self.nArm_comboBox.addItem("")
        self.nArm_comboBox.addItem("")
        self.nArm_comboBox.addItem("")
        self.gridLayout.addWidget(self.nArm_comboBox, 13, 2, 1, 1)
        self.predSuccess_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.predSuccess_textCtl.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.predSuccess_textCtl.setFont(font)
        self.predSuccess_textCtl.setUpdatesEnabled(True)
        self.predSuccess_textCtl.setVisible(True)
        self.predSuccess_textCtl.setWindowTitle("")
        self.predSuccess_textCtl.setWindowIconText("")
        self.predSuccess_textCtl.setWindowOpacity(1.0)
        self.predSuccess_textCtl.setWindowModified(False)
        self.predSuccess_textCtl.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.predSuccess_textCtl.setWindowFilePath("")
        self.predSuccess_textCtl.setModified(False)
        self.predSuccess_textCtl.setObjectName("predSuccess_textCtl")
        self.gridLayout.addWidget(self.predSuccess_textCtl, 34, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem9, 8, 0, 1, 1)
        self.seed_checkBox = QtWidgets.QCheckBox(self.settingContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seed_checkBox.sizePolicy().hasHeightForWidth())
        self.seed_checkBox.setSizePolicy(sizePolicy)
        self.seed_checkBox.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.seed_checkBox.setFont(font)
        self.seed_checkBox.setChecked(False)
        self.seed_checkBox.setObjectName("seed_checkBox")
        self.gridLayout.addWidget(self.seed_checkBox, 8, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 26, 1, 1, 1)
        self.nArm_Label = QtWidgets.QLabel(self.settingContent)
        self.nArm_Label.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.nArm_Label.setFont(font)
        self.nArm_Label.setObjectName("nArm_Label")
        self.gridLayout.addWidget(self.nArm_Label, 13, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem11, 19, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem12, 24, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 22, 1, 1, 1)
        self.alloc_Label = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.alloc_Label.setFont(font)
        self.alloc_Label.setWordWrap(True)
        self.alloc_Label.setObjectName("alloc_Label")
        self.gridLayout.addWidget(self.alloc_Label, 24, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 12, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 7, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem16, 0, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem17, 38, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem18, 3, 1, 1, 1)
        self.alloc_textCtl = QtWidgets.QLineEdit(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.alloc_textCtl.setFont(font)
        self.alloc_textCtl.setStyleSheet("")
        self.alloc_textCtl.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.alloc_textCtl.setObjectName("alloc_textCtl")
        self.gridLayout.addWidget(self.alloc_textCtl, 24, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem19, 16, 1, 1, 1)
        self.sim_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.sim_textCtl.setMaximumSize(QtCore.QSize(202, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.sim_textCtl.setFont(font)
        self.sim_textCtl.setText("")
        self.sim_textCtl.setObjectName("sim_textCtl")
        self.gridLayout.addWidget(self.sim_textCtl, 5, 2, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem20, 28, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem21, 30, 1, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem22, 2, 0, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem23, 33, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.settingContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMaximumSize(QtCore.QSize(16777215, 2))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line.setFont(font)
        self.line.setStyleSheet("QWidget{\n"
"     background-color:#399ee5;\n"
"}")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(-3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 1, 1, 6)
        self.line_2 = QtWidgets.QFrame(self.settingContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 2))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("QWidget{\n"
"     background-color:#399ee5;\n"
"}")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(-3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 11, 1, 1, 6)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem24, 18, 1, 1, 1)
        self.predClinSig_checkBox = QtWidgets.QCheckBox(self.settingContent)
        self.predClinSig_checkBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predClinSig_checkBox.sizePolicy().hasHeightForWidth())
        self.predClinSig_checkBox.setSizePolicy(sizePolicy)
        self.predClinSig_checkBox.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.predClinSig_checkBox.setFont(font)
        self.predClinSig_checkBox.setChecked(False)
        self.predClinSig_checkBox.setObjectName("predClinSig_checkBox")
        self.gridLayout.addWidget(self.predClinSig_checkBox, 36, 1, 1, 2)
        self.predNum_btn = QtWidgets.QPushButton(self.settingContent)
        self.predNum_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.predNum_btn.setFont(font)
        self.predNum_btn.setObjectName("predNum_btn")
        self.gridLayout.addWidget(self.predNum_btn, 31, 2, 1, 1)
        self.clinSig_Label = QtWidgets.QLabel(self.settingContent)
        self.clinSig_Label.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.clinSig_Label.setFont(font)
        self.clinSig_Label.setWordWrap(True)
        self.clinSig_Label.setObjectName("clinSig_Label")
        self.gridLayout.addWidget(self.clinSig_Label, 27, 1, 1, 1)
        self.predClinSig_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.predClinSig_textCtl.setEnabled(False)
        self.predClinSig_textCtl.setMaximumSize(QtCore.QSize(202, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.predClinSig_textCtl.setFont(font)
        self.predClinSig_textCtl.setObjectName("predClinSig_textCtl")
        self.gridLayout.addWidget(self.predClinSig_textCtl, 36, 3, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem25, 35, 1, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem26, 27, 0, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem27, 9, 1, 1, 1)
        self.predSuccess_Label = QtWidgets.QLabel(self.settingContent)
        self.predSuccess_Label.setEnabled(False)
        self.predSuccess_Label.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.predSuccess_Label.setFont(font)
        self.predSuccess_Label.setWordWrap(True)
        self.predSuccess_Label.setObjectName("predSuccess_Label")
        self.gridLayout.addWidget(self.predSuccess_Label, 34, 1, 1, 1)
        self.nStage_comboBox = QtWidgets.QComboBox(self.settingContent)
        self.nStage_comboBox.setMaximumSize(QtCore.QSize(202, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.nStage_comboBox.setFont(font)
        self.nStage_comboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.nStage_comboBox.setObjectName("nStage_comboBox")
        self.nStage_comboBox.addItem("")
        self.nStage_comboBox.addItem("")
        self.nStage_comboBox.addItem("")
        self.nStage_comboBox.addItem("")
        self.nStage_comboBox.addItem("")
        self.gridLayout.addWidget(self.nStage_comboBox, 19, 2, 1, 1)
        self.assignPatient_btn = QtWidgets.QPushButton(self.settingContent)
        self.assignPatient_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.assignPatient_btn.setFont(font)
        self.assignPatient_btn.setObjectName("assignPatient_btn")
        self.gridLayout.addWidget(self.assignPatient_btn, 19, 3, 1, 1)
        self.prior_Frame = QtWidgets.QFrame(self.settingContent)
        self.prior_Frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.prior_Frame.setStyleSheet("QFrame#prior_Frame{\n"
"     border: 1px solid #399ee5;\n"
"     border-radius： 5px;\n"
"     border-left: 3px solid #399ee5;\n"
"}")
        self.prior_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.prior_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.prior_Frame.setObjectName("prior_Frame")
        self.formLayout_3 = QtWidgets.QFormLayout(self.prior_Frame)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_3.setContentsMargins(20, 20, 20, 20)
        self.formLayout_3.setObjectName("formLayout_3")
        self.prior_tableWidget = QtWidgets.QTableWidget(self.prior_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prior_tableWidget.sizePolicy().hasHeightForWidth())
        self.prior_tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.prior_tableWidget.setFont(font)
        self.prior_tableWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.prior_tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.prior_tableWidget.setStyleSheet("QLineEdit{\n"
"    min-width: 80px;\n"
"    max-width: 1000px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}")
        self.prior_tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.prior_tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.prior_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.prior_tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.prior_tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.prior_tableWidget.setObjectName("prior_tableWidget")
        self.prior_tableWidget.setColumnCount(0)
        self.prior_tableWidget.setRowCount(0)
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.prior_tableWidget)
        self.cancelPrior_btn = QtWidgets.QToolButton(self.prior_Frame)
        self.cancelPrior_btn.setStyleSheet("QToolButton:hover{\n"
"     background: #cce5f3;\n"
"     border: 1px solid #fafbfc;\n"
"}\n"
"")
        self.cancelPrior_btn.setIcon(icon)
        self.cancelPrior_btn.setObjectName("cancelPrior_btn")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cancelPrior_btn)
        self.savePrior_btn = QtWidgets.QPushButton(self.prior_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.savePrior_btn.setFont(font)
        self.savePrior_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.savePrior_btn.setObjectName("savePrior_btn")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.savePrior_btn)
        self.resetPrior_btn = QtWidgets.QPushButton(self.prior_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.resetPrior_btn.setFont(font)
        self.resetPrior_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetPrior_btn.setObjectName("resetPrior_btn")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.resetPrior_btn)
        self.gridLayout.addWidget(self.prior_Frame, 17, 1, 1, 4)
        self.predNum_Frame = QtWidgets.QFrame(self.settingContent)
        self.predNum_Frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.predNum_Frame.setStyleSheet("QFrame#predNum_Frame{\n"
"     border: 1px solid #399ee5;\n"
"     border-radius： 5px;\n"
"     border-left: 3px solid #399ee5;\n"
"}")
        self.predNum_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.predNum_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.predNum_Frame.setObjectName("predNum_Frame")
        self.formLayout_5 = QtWidgets.QFormLayout(self.predNum_Frame)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_5.setContentsMargins(20, 20, 20, 20)
        self.formLayout_5.setObjectName("formLayout_5")
        self.cancelPredNum_btn = QtWidgets.QToolButton(self.predNum_Frame)
        self.cancelPredNum_btn.setStyleSheet("QToolButton:hover{\n"
"     background: #cce5f3;\n"
"     border: 1px solid #fafbfc;\n"
"}\n"
"")
        self.cancelPredNum_btn.setIcon(icon)
        self.cancelPredNum_btn.setObjectName("cancelPredNum_btn")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cancelPredNum_btn)
        self.predNum_tableWidget = QtWidgets.QTableWidget(self.predNum_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predNum_tableWidget.sizePolicy().hasHeightForWidth())
        self.predNum_tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.predNum_tableWidget.setFont(font)
        self.predNum_tableWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.predNum_tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.predNum_tableWidget.setStyleSheet("QLineEdit{\n"
"    min-width: 80px;\n"
"    max-width: 1000px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}\n"
"")
        self.predNum_tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.predNum_tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.predNum_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.predNum_tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.predNum_tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.predNum_tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.predNum_tableWidget.setObjectName("predNum_tableWidget")
        self.predNum_tableWidget.setColumnCount(0)
        self.predNum_tableWidget.setRowCount(0)
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.predNum_tableWidget)
        self.resetPredNum_btn = QtWidgets.QPushButton(self.predNum_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.resetPredNum_btn.setFont(font)
        self.resetPredNum_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetPredNum_btn.setObjectName("resetPredNum_btn")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.resetPredNum_btn)
        self.savePredNum_btn = QtWidgets.QPushButton(self.predNum_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.savePredNum_btn.setFont(font)
        self.savePredNum_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.savePredNum_btn.setObjectName("savePredNum_btn")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.savePredNum_btn)
        self.gridLayout.addWidget(self.predNum_Frame, 32, 1, 1, 4)
        self.setPrior_btn = QtWidgets.QPushButton(self.settingContent)
        self.setPrior_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.setPrior_btn.setFont(font)
        self.setPrior_btn.setObjectName("setPrior_btn")
        self.gridLayout.addWidget(self.setPrior_btn, 14, 3, 1, 1)
        self.setStopBoundary_btn = QtWidgets.QPushButton(self.settingContent)
        self.setStopBoundary_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.setStopBoundary_btn.setFont(font)
        self.setStopBoundary_btn.setObjectName("setStopBoundary_btn")
        self.gridLayout.addWidget(self.setStopBoundary_btn, 20, 3, 1, 1)
        self.seed_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.seed_textCtl.setEnabled(False)
        self.seed_textCtl.setMaximumSize(QtCore.QSize(202, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.seed_textCtl.setFont(font)
        self.seed_textCtl.setText("")
        self.seed_textCtl.setPlaceholderText("")
        self.seed_textCtl.setObjectName("seed_textCtl")
        self.gridLayout.addWidget(self.seed_textCtl, 8, 2, 1, 1)
        self.settingArea.setWidget(self.settingContent)
        self.verticalLayout.addWidget(self.settingArea)

        self.retranslateUi(MAMSWindow)
        self.nArm_comboBox.setCurrentIndex(-1)
        self.nStage_comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MAMSWindow)
        MAMSWindow.setTabOrder(self.sim_textCtl, self.seed_checkBox)
        MAMSWindow.setTabOrder(self.seed_checkBox, self.seed_textCtl)
        MAMSWindow.setTabOrder(self.seed_textCtl, self.nArm_comboBox)
        MAMSWindow.setTabOrder(self.nArm_comboBox, self.trtEffSize_btn)
        MAMSWindow.setTabOrder(self.trtEffSize_btn, self.cancelEff_btn)
        MAMSWindow.setTabOrder(self.cancelEff_btn, self.effSize_tableWidget)
        MAMSWindow.setTabOrder(self.effSize_tableWidget, self.saveEff_btn)
        MAMSWindow.setTabOrder(self.saveEff_btn, self.resetEff_btn)
        MAMSWindow.setTabOrder(self.resetEff_btn, self.nStage_comboBox)
        MAMSWindow.setTabOrder(self.nStage_comboBox, self.assignPatient_btn)
        MAMSWindow.setTabOrder(self.assignPatient_btn, self.cancelPat_btn)
        MAMSWindow.setTabOrder(self.cancelPat_btn, self.patNum_tableWidget)
        MAMSWindow.setTabOrder(self.patNum_tableWidget, self.savePat_btn)
        MAMSWindow.setTabOrder(self.savePat_btn, self.resetPat_btn)
        MAMSWindow.setTabOrder(self.resetPat_btn, self.alloc_textCtl)
        MAMSWindow.setTabOrder(self.alloc_textCtl, self.clinSig_textCtl)
        MAMSWindow.setTabOrder(self.clinSig_textCtl, self.predict_checkBox)
        MAMSWindow.setTabOrder(self.predict_checkBox, self.predSuccess_textCtl)
        MAMSWindow.setTabOrder(self.predSuccess_textCtl, self.predClinSig_checkBox)
        MAMSWindow.setTabOrder(self.predClinSig_checkBox, self.predClinSig_textCtl)

    def retranslateUi(self, MAMSWindow):
        _translate = QtCore.QCoreApplication.translate
        MAMSWindow.setWindowTitle(_translate("MAMSWindow", "Form"))
        self.trtEffSize_btn.setText(_translate("MAMSWindow", "Treatment Effects"))
        self.cancelBoundary_btn.setText(_translate("MAMSWindow", "..."))
        self.resetBoundary_btn.setText(_translate("MAMSWindow", "Reset"))
        self.saveBoundary_btn.setText(_translate("MAMSWindow", "Save"))
        self.cancelPat_btn.setText(_translate("MAMSWindow", "..."))
        self.resetPat_btn.setText(_translate("MAMSWindow", "Reset"))
        self.savePat_btn.setText(_translate("MAMSWindow", "Save"))
        self.cancelEff_btn.setText(_translate("MAMSWindow", "..."))
        self.saveEff_btn.setText(_translate("MAMSWindow", "Save"))
        self.resetEff_btn.setText(_translate("MAMSWindow", "Reset"))
        self.nStage_Label.setText(_translate("MAMSWindow", "Number of Stages:"))
        self.predict_checkBox.setText(_translate("MAMSWindow", "Predictive Probability:"))
        self.label.setText(_translate("MAMSWindow", "Simulation Setting"))
        self.sim_Label.setText(_translate("MAMSWindow", "Number of Simulations:"))
        self.predNum_Label.setText(_translate("MAMSWindow", "Number of New Patients:"))
        self.clinSig_textCtl.setPlaceholderText(_translate("MAMSWindow", "0 to 1"))
        self.label_2.setText(_translate("MAMSWindow", "Trial Parameters"))
        self.nArm_comboBox.setItemText(0, _translate("MAMSWindow", "2"))
        self.nArm_comboBox.setItemText(1, _translate("MAMSWindow", "3"))
        self.nArm_comboBox.setItemText(2, _translate("MAMSWindow", "4"))
        self.nArm_comboBox.setItemText(3, _translate("MAMSWindow", "5"))
        self.nArm_comboBox.setItemText(4, _translate("MAMSWindow", "6"))
        self.nArm_comboBox.setItemText(5, _translate("MAMSWindow", "7"))
        self.nArm_comboBox.setItemText(6, _translate("MAMSWindow", "8"))
        self.nArm_comboBox.setItemText(7, _translate("MAMSWindow", "9"))
        self.nArm_comboBox.setItemText(8, _translate("MAMSWindow", "10"))
        self.predSuccess_textCtl.setPlaceholderText(_translate("MAMSWindow", "0 to 1"))
        self.seed_checkBox.setText(_translate("MAMSWindow", "Seed:"))
        self.nArm_Label.setText(_translate("MAMSWindow", "Number of Arms:"))
        self.alloc_Label.setText(_translate("MAMSWindow", "Allocation Ratio (Control to Treatment):"))
        self.alloc_textCtl.setPlaceholderText(_translate("MAMSWindow", "1 to 4"))
        self.sim_textCtl.setPlaceholderText(_translate("MAMSWindow", "1000 to 100000"))
        self.predClinSig_checkBox.setText(_translate("MAMSWindow", "Use Same Clinically Significant Difference Or"))
        self.predNum_btn.setText(_translate("MAMSWindow", "Assign New Patients"))
        self.clinSig_Label.setText(_translate("MAMSWindow", "Clinically Significant Difference:"))
        self.predSuccess_Label.setText(_translate("MAMSWindow", "Success Boundary:"))
        self.nStage_comboBox.setItemText(0, _translate("MAMSWindow", "2"))
        self.nStage_comboBox.setItemText(1, _translate("MAMSWindow", "3"))
        self.nStage_comboBox.setItemText(2, _translate("MAMSWindow", "4"))
        self.nStage_comboBox.setItemText(3, _translate("MAMSWindow", "5"))
        self.nStage_comboBox.setItemText(4, _translate("MAMSWindow", "6"))
        self.assignPatient_btn.setText(_translate("MAMSWindow", "Assign Patients"))
        self.cancelPrior_btn.setText(_translate("MAMSWindow", "..."))
        self.savePrior_btn.setText(_translate("MAMSWindow", "Save"))
        self.resetPrior_btn.setText(_translate("MAMSWindow", "Reset"))
        self.cancelPredNum_btn.setText(_translate("MAMSWindow", "..."))
        self.resetPredNum_btn.setText(_translate("MAMSWindow", "Reset"))
        self.savePredNum_btn.setText(_translate("MAMSWindow", "Save"))
        self.setPrior_btn.setText(_translate("MAMSWindow", "Set Prior"))
        self.setStopBoundary_btn.setText(_translate("MAMSWindow", "Set Boundary"))

