# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PosteriorProbabilityWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PosteriorProbabilityWindow(object):
    def setupUi(self, PosteriorProbabilityWindow):
        PosteriorProbabilityWindow.setObjectName("PosteriorProbabilityWindow")
        PosteriorProbabilityWindow.resize(884, 900)
        self.verticalLayout = QtWidgets.QVBoxLayout(PosteriorProbabilityWindow)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingArea = QtWidgets.QScrollArea(PosteriorProbabilityWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.settingArea.setFont(font)
        self.settingArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.settingArea.setWidgetResizable(True)
        self.settingArea.setObjectName("settingArea")
        self.settingContent = QtWidgets.QWidget()
        self.settingContent.setGeometry(QtCore.QRect(0, -35, 856, 974))
        self.settingContent.setObjectName("settingContent")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.settingContent)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.controlPriorB_Label = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.controlPriorB_Label.setFont(font)
        self.controlPriorB_Label.setObjectName("controlPriorB_Label")
        self.gridLayout_2.addWidget(self.controlPriorB_Label, 16, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 1, 1, 2)
        self.nSuccessTrt_Label = QtWidgets.QLabel(self.settingContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nSuccessTrt_Label.sizePolicy().hasHeightForWidth())
        self.nSuccessTrt_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.nSuccessTrt_Label.setFont(font)
        self.nSuccessTrt_Label.setWordWrap(True)
        self.nSuccessTrt_Label.setObjectName("nSuccessTrt_Label")
        self.gridLayout_2.addWidget(self.nSuccessTrt_Label, 5, 1, 1, 1)
        self.nFailTrt_Label = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.nFailTrt_Label.setFont(font)
        self.nFailTrt_Label.setWordWrap(True)
        self.nFailTrt_Label.setObjectName("nFailTrt_Label")
        self.gridLayout_2.addWidget(self.nFailTrt_Label, 7, 1, 1, 1)
        self.clinSig_Label = QtWidgets.QLabel(self.settingContent)
        self.clinSig_Label.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.clinSig_Label.setFont(font)
        self.clinSig_Label.setWordWrap(True)
        self.clinSig_Label.setObjectName("clinSig_Label")
        self.gridLayout_2.addWidget(self.clinSig_Label, 20, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.settingContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setMaximumSize(QtCore.QSize(16777215, 2))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line_4.setFont(font)
        self.line_4.setStyleSheet("QWidget{\n"
"     background-color:#399ee5;\n"
"}")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(-3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 3, 1, 1, 7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 24, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 7, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem4, 5, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 8, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem6, 20, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 21, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 6, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 11, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.settingContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setMaximumSize(QtCore.QSize(16777215, 2))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line_6.setFont(font)
        self.line_6.setStyleSheet("QWidget{\n"
"     background-color:#399ee5;\n"
"}")
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(-3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 19, 1, 1, 7)
        self.line_5 = QtWidgets.QFrame(self.settingContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setMaximumSize(QtCore.QSize(16777215, 2))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line_5.setFont(font)
        self.line_5.setStyleSheet("QWidget{\n"
"     background-color:#399ee5;\n"
"}")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(-3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 12, 1, 1, 7)
        self.nSuccessTrt_textCtl = QtWidgets.QLineEdit(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.nSuccessTrt_textCtl.setFont(font)
        self.nSuccessTrt_textCtl.setObjectName("nSuccessTrt_textCtl")
        self.gridLayout_2.addWidget(self.nSuccessTrt_textCtl, 5, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 5, 3, 1, 1)
        self.nFailTrt_textCtl = QtWidgets.QLineEdit(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.nFailTrt_textCtl.setFont(font)
        self.nFailTrt_textCtl.setObjectName("nFailTrt_textCtl")
        self.gridLayout_2.addWidget(self.nFailTrt_textCtl, 7, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 3, 0, 1, 1)
        self.trtPrior_Label = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trtPrior_Label.setFont(font)
        self.trtPrior_Label.setObjectName("trtPrior_Label")
        self.gridLayout_2.addWidget(self.trtPrior_Label, 9, 1, 1, 1)
        self.nFailControl_Label = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nFailControl_Label.setFont(font)
        self.nFailControl_Label.setWordWrap(True)
        self.nFailControl_Label.setObjectName("nFailControl_Label")
        self.gridLayout_2.addWidget(self.nFailControl_Label, 15, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem11, 13, 3, 1, 1)
        self.controlPriorB_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.controlPriorB_textCtl.setObjectName("controlPriorB_textCtl")
        self.gridLayout_2.addWidget(self.controlPriorB_textCtl, 17, 3, 1, 1)
        self.nFailControl_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.nFailControl_textCtl.setObjectName("nFailControl_textCtl")
        self.gridLayout_2.addWidget(self.nFailControl_textCtl, 15, 2, 1, 1)
        self.trtPriorA_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.trtPriorA_textCtl.setObjectName("trtPriorA_textCtl")
        self.gridLayout_2.addWidget(self.trtPriorA_textCtl, 9, 2, 1, 1)
        self.trtPriorA_Label = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trtPriorA_Label.setFont(font)
        self.trtPriorA_Label.setObjectName("trtPriorA_Label")
        self.gridLayout_2.addWidget(self.trtPriorA_Label, 8, 2, 1, 1)
        self.nSuccessControl_Label = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nSuccessControl_Label.setFont(font)
        self.nSuccessControl_Label.setWordWrap(True)
        self.nSuccessControl_Label.setObjectName("nSuccessControl_Label")
        self.gridLayout_2.addWidget(self.nSuccessControl_Label, 13, 1, 1, 1)
        self.trtPriorB_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.trtPriorB_textCtl.setObjectName("trtPriorB_textCtl")
        self.gridLayout_2.addWidget(self.trtPriorB_textCtl, 9, 3, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 10, 1, 1, 1)
        self.trtPriorB_Label = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trtPriorB_Label.setFont(font)
        self.trtPriorB_Label.setObjectName("trtPriorB_Label")
        self.gridLayout_2.addWidget(self.trtPriorB_Label, 8, 3, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem13, 7, 3, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem14, 14, 1, 1, 1)
        self.controlPrior_Label = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.controlPrior_Label.setFont(font)
        self.controlPrior_Label.setObjectName("controlPrior_Label")
        self.gridLayout_2.addWidget(self.controlPrior_Label, 17, 1, 1, 1)
        self.controlPriorA_Label = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.controlPriorA_Label.setFont(font)
        self.controlPriorA_Label.setObjectName("controlPriorA_Label")
        self.gridLayout_2.addWidget(self.controlPriorA_Label, 16, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem15, 16, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem16, 18, 1, 1, 1)
        self.nSuccessControl_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.nSuccessControl_textCtl.setObjectName("nSuccessControl_textCtl")
        self.gridLayout_2.addWidget(self.nSuccessControl_textCtl, 13, 2, 1, 1)
        self.controlPriorA_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.controlPriorA_textCtl.setObjectName("controlPriorA_textCtl")
        self.gridLayout_2.addWidget(self.controlPriorA_textCtl, 17, 2, 1, 1)
        self.seed_checkBox = QtWidgets.QCheckBox(self.settingContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seed_checkBox.sizePolicy().hasHeightForWidth())
        self.seed_checkBox.setSizePolicy(sizePolicy)
        self.seed_checkBox.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.seed_checkBox.setFont(font)
        self.seed_checkBox.setChecked(False)
        self.seed_checkBox.setObjectName("seed_checkBox")
        self.gridLayout_2.addWidget(self.seed_checkBox, 22, 1, 1, 1)
        self.seed_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.seed_textCtl.setEnabled(False)
        self.seed_textCtl.setMaximumSize(QtCore.QSize(202, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.seed_textCtl.setFont(font)
        self.seed_textCtl.setText("")
        self.seed_textCtl.setPlaceholderText("")
        self.seed_textCtl.setObjectName("seed_textCtl")
        self.gridLayout_2.addWidget(self.seed_textCtl, 22, 2, 1, 3)
        self.clinSig_textCtl = QtWidgets.QLineEdit(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.clinSig_textCtl.setFont(font)
        self.clinSig_textCtl.setUpdatesEnabled(True)
        self.clinSig_textCtl.setVisible(True)
        self.clinSig_textCtl.setWindowTitle("")
        self.clinSig_textCtl.setWindowIconText("")
        self.clinSig_textCtl.setWindowOpacity(1.0)
        self.clinSig_textCtl.setWindowModified(False)
        self.clinSig_textCtl.setWindowFilePath("")
        self.clinSig_textCtl.setModified(False)
        self.clinSig_textCtl.setObjectName("clinSig_textCtl")
        self.gridLayout_2.addWidget(self.clinSig_textCtl, 20, 2, 1, 2)
        self.settingArea.setWidget(self.settingContent)
        self.verticalLayout.addWidget(self.settingArea)

        self.retranslateUi(PosteriorProbabilityWindow)
        QtCore.QMetaObject.connectSlotsByName(PosteriorProbabilityWindow)
        PosteriorProbabilityWindow.setTabOrder(self.nSuccessTrt_textCtl, self.nFailTrt_textCtl)
        PosteriorProbabilityWindow.setTabOrder(self.nFailTrt_textCtl, self.trtPriorA_textCtl)
        PosteriorProbabilityWindow.setTabOrder(self.trtPriorA_textCtl, self.trtPriorB_textCtl)
        PosteriorProbabilityWindow.setTabOrder(self.trtPriorB_textCtl, self.nSuccessControl_textCtl)
        PosteriorProbabilityWindow.setTabOrder(self.nSuccessControl_textCtl, self.nFailControl_textCtl)
        PosteriorProbabilityWindow.setTabOrder(self.nFailControl_textCtl, self.controlPriorA_textCtl)
        PosteriorProbabilityWindow.setTabOrder(self.controlPriorA_textCtl, self.controlPriorB_textCtl)
        PosteriorProbabilityWindow.setTabOrder(self.controlPriorB_textCtl, self.clinSig_textCtl)
        PosteriorProbabilityWindow.setTabOrder(self.clinSig_textCtl, self.seed_checkBox)
        PosteriorProbabilityWindow.setTabOrder(self.seed_checkBox, self.seed_textCtl)
        PosteriorProbabilityWindow.setTabOrder(self.seed_textCtl, self.settingArea)

    def retranslateUi(self, PosteriorProbabilityWindow):
        _translate = QtCore.QCoreApplication.translate
        PosteriorProbabilityWindow.setWindowTitle(_translate("PosteriorProbabilityWindow", "Form"))
        self.controlPriorB_Label.setText(_translate("PosteriorProbabilityWindow", "Prior B"))
        self.label_3.setText(_translate("PosteriorProbabilityWindow", "Treatment Arm"))
        self.nSuccessTrt_Label.setText(_translate("PosteriorProbabilityWindow", "Number of Success in Treatment："))
        self.nFailTrt_Label.setText(_translate("PosteriorProbabilityWindow", "Number of Failures in Treatment:"))
        self.clinSig_Label.setText(_translate("PosteriorProbabilityWindow", "Clinically Significant Difference:"))
        self.label_12.setText(_translate("PosteriorProbabilityWindow", "Control Arm"))
        self.trtPrior_Label.setText(_translate("PosteriorProbabilityWindow", "Prior of Treatment"))
        self.nFailControl_Label.setText(_translate("PosteriorProbabilityWindow", "Number of Failures in Control:"))
        self.trtPriorA_Label.setText(_translate("PosteriorProbabilityWindow", "Prior A"))
        self.nSuccessControl_Label.setText(_translate("PosteriorProbabilityWindow", "Number of Success in Control："))
        self.trtPriorB_Label.setText(_translate("PosteriorProbabilityWindow", "Prior B"))
        self.controlPrior_Label.setText(_translate("PosteriorProbabilityWindow", "Prior of Control"))
        self.controlPriorA_Label.setText(_translate("PosteriorProbabilityWindow", "Prior A"))
        self.seed_checkBox.setText(_translate("PosteriorProbabilityWindow", "Seed:"))
        self.clinSig_textCtl.setPlaceholderText(_translate("PosteriorProbabilityWindow", "0-1"))

