# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MAMSWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MAMSWindow(object):
    def setupUi(self, MAMSWindow):
        MAMSWindow.setObjectName("MAMSWindow")
        MAMSWindow.resize(850, 950)
        self.verticalLayout = QtWidgets.QVBoxLayout(MAMSWindow)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingArea = QtWidgets.QScrollArea(MAMSWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.settingArea.setFont(font)
        self.settingArea.setFocusPolicy(QtCore.Qt.NoFocus)
        self.settingArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.settingArea.setWidgetResizable(True)
        self.settingArea.setObjectName("settingArea")
        self.settingContent = QtWidgets.QWidget()
        self.settingContent.setGeometry(QtCore.QRect(0, -1266, 822, 2375))
        self.settingContent.setObjectName("settingContent")
        self.gridLayout = QtWidgets.QGridLayout(self.settingContent)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_15 = QtWidgets.QLabel(self.settingContent)
        self.label_15.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 23, 1, 1, 1)
        self.eff_textCtl = QtWidgets.QLineEdit(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.eff_textCtl.setFont(font)
        self.eff_textCtl.setUpdatesEnabled(True)
        self.eff_textCtl.setVisible(True)
        self.eff_textCtl.setWindowTitle("")
        self.eff_textCtl.setWindowIconText("")
        self.eff_textCtl.setWindowOpacity(1.0)
        self.eff_textCtl.setWindowModified(False)
        self.eff_textCtl.setWindowFilePath("")
        self.eff_textCtl.setModified(False)
        self.eff_textCtl.setObjectName("eff_textCtl")
        self.gridLayout.addWidget(self.eff_textCtl, 23, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 23, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.settingContent)
        self.label_14.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 21, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 21, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.settingContent)
        self.label_5.setMinimumSize(QtCore.QSize(200, 50))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 2, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 10, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 10, 1, 1, 4)
        self.clinSig_textCtl = QtWidgets.QLineEdit(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.clinSig_textCtl.setFont(font)
        self.clinSig_textCtl.setUpdatesEnabled(True)
        self.clinSig_textCtl.setVisible(True)
        self.clinSig_textCtl.setWindowTitle("")
        self.clinSig_textCtl.setWindowIconText("")
        self.clinSig_textCtl.setWindowOpacity(1.0)
        self.clinSig_textCtl.setWindowModified(False)
        self.clinSig_textCtl.setWindowFilePath("")
        self.clinSig_textCtl.setModified(False)
        self.clinSig_textCtl.setObjectName("clinSig_textCtl")
        self.gridLayout.addWidget(self.clinSig_textCtl, 25, 3, 1, 1)
        self.predNum_Label = QtWidgets.QLabel(self.settingContent)
        self.predNum_Label.setEnabled(False)
        self.predNum_Label.setMinimumSize(QtCore.QSize(0, 0))
        self.predNum_Label.setMaximumSize(QtCore.QSize(16777215, 10000))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.predNum_Label.setFont(font)
        self.predNum_Label.setLineWidth(1)
        self.predNum_Label.setScaledContents(False)
        self.predNum_Label.setWordWrap(True)
        self.predNum_Label.setObjectName("predNum_Label")
        self.gridLayout.addWidget(self.predNum_Label, 29, 1, 1, 1)
        self.nArm_comboBox = QtWidgets.QComboBox(self.settingContent)
        self.nArm_comboBox.setMaximumSize(QtCore.QSize(202, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.nArm_comboBox.setFont(font)
        self.nArm_comboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.nArm_comboBox.setStyleSheet("")
        self.nArm_comboBox.setObjectName("nArm_comboBox")
        self.nArm_comboBox.addItem("")
        self.nArm_comboBox.addItem("")
        self.nArm_comboBox.addItem("")
        self.nArm_comboBox.addItem("")
        self.nArm_comboBox.addItem("")
        self.nArm_comboBox.addItem("")
        self.nArm_comboBox.addItem("")
        self.nArm_comboBox.addItem("")
        self.gridLayout.addWidget(self.nArm_comboBox, 13, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 24, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 8, 0, 1, 1)
        self.seed_checkBox = QtWidgets.QCheckBox(self.settingContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seed_checkBox.sizePolicy().hasHeightForWidth())
        self.seed_checkBox.setSizePolicy(sizePolicy)
        self.seed_checkBox.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.seed_checkBox.setFont(font)
        self.seed_checkBox.setChecked(False)
        self.seed_checkBox.setObjectName("seed_checkBox")
        self.gridLayout.addWidget(self.seed_checkBox, 8, 1, 1, 1)
        self.predSuccess_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.predSuccess_textCtl.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.predSuccess_textCtl.setFont(font)
        self.predSuccess_textCtl.setUpdatesEnabled(True)
        self.predSuccess_textCtl.setVisible(True)
        self.predSuccess_textCtl.setWindowTitle("")
        self.predSuccess_textCtl.setWindowIconText("")
        self.predSuccess_textCtl.setWindowOpacity(1.0)
        self.predSuccess_textCtl.setWindowModified(False)
        self.predSuccess_textCtl.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.predSuccess_textCtl.setWindowFilePath("")
        self.predSuccess_textCtl.setModified(False)
        self.predSuccess_textCtl.setObjectName("predSuccess_textCtl")
        self.gridLayout.addWidget(self.predSuccess_textCtl, 31, 3, 1, 1)
        self.loadCVL_checkBox = QtWidgets.QCheckBox(self.settingContent)
        self.loadCVL_checkBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadCVL_checkBox.sizePolicy().hasHeightForWidth())
        self.loadCVL_checkBox.setSizePolicy(sizePolicy)
        self.loadCVL_checkBox.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.loadCVL_checkBox.setFont(font)
        self.loadCVL_checkBox.setUpdatesEnabled(True)
        self.loadCVL_checkBox.setVisible(True)
        self.loadCVL_checkBox.setWindowTitle("")
        self.loadCVL_checkBox.setWindowIconText("")
        self.loadCVL_checkBox.setWindowOpacity(1.0)
        self.loadCVL_checkBox.setWindowModified(False)
        self.loadCVL_checkBox.setStyleSheet("")
        self.loadCVL_checkBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.loadCVL_checkBox.setWindowFilePath("")
        self.loadCVL_checkBox.setDown(False)
        self.loadCVL_checkBox.setObjectName("loadCVL_checkBox")
        self.gridLayout.addWidget(self.loadCVL_checkBox, 38, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 31, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 38, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.settingContent)
        self.label_12.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 13, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem8, 13, 0, 1, 1)
        self.predNum_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.predNum_textCtl.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.predNum_textCtl.setFont(font)
        self.predNum_textCtl.setUpdatesEnabled(True)
        self.predNum_textCtl.setVisible(True)
        self.predNum_textCtl.setWindowTitle("")
        self.predNum_textCtl.setWindowIconText("")
        self.predNum_textCtl.setWindowOpacity(1.0)
        self.predNum_textCtl.setWindowModified(False)
        self.predNum_textCtl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.predNum_textCtl.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.predNum_textCtl.setWindowFilePath("")
        self.predNum_textCtl.setFrame(True)
        self.predNum_textCtl.setModified(False)
        self.predNum_textCtl.setPlaceholderText("")
        self.predNum_textCtl.setObjectName("predNum_textCtl")
        self.gridLayout.addWidget(self.predNum_textCtl, 29, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 16, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem9, 16, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem10, 19, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 19, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 18, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem12, 29, 0, 1, 1)
        self.predict_checkBox = QtWidgets.QCheckBox(self.settingContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predict_checkBox.sizePolicy().hasHeightForWidth())
        self.predict_checkBox.setSizePolicy(sizePolicy)
        self.predict_checkBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.predict_checkBox.setFont(font)
        self.predict_checkBox.setChecked(False)
        self.predict_checkBox.setObjectName("predict_checkBox")
        self.gridLayout.addWidget(self.predict_checkBox, 27, 1, 1, 3)
        spacerItem13 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem13, 27, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.settingContent)
        self.label_16.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 25, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem14, 25, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 32, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem16, 36, 0, 1, 1)
        self.search_Label = QtWidgets.QLabel(self.settingContent)
        self.search_Label.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.search_Label.setFont(font)
        self.search_Label.setWordWrap(True)
        self.search_Label.setObjectName("search_Label")
        self.gridLayout.addWidget(self.search_Label, 36, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem17, 33, 0, 1, 1)
        self.predSuccess_Label = QtWidgets.QLabel(self.settingContent)
        self.predSuccess_Label.setEnabled(False)
        self.predSuccess_Label.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.predSuccess_Label.setFont(font)
        self.predSuccess_Label.setWordWrap(True)
        self.predSuccess_Label.setObjectName("predSuccess_Label")
        self.gridLayout.addWidget(self.predSuccess_Label, 31, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem18, 20, 1, 1, 1)
        self.fut_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.fut_textCtl.setMaximumSize(QtCore.QSize(202, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.fut_textCtl.setFont(font)
        self.fut_textCtl.setUpdatesEnabled(True)
        self.fut_textCtl.setVisible(True)
        self.fut_textCtl.setWindowTitle("")
        self.fut_textCtl.setWindowIconText("")
        self.fut_textCtl.setWindowOpacity(1.0)
        self.fut_textCtl.setWindowModified(False)
        self.fut_textCtl.setWindowFilePath("")
        self.fut_textCtl.setText("")
        self.fut_textCtl.setModified(False)
        self.fut_textCtl.setObjectName("fut_textCtl")
        self.gridLayout.addWidget(self.fut_textCtl, 21, 3, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem19, 9, 1, 1, 1)
        self.nStage_comboBox = QtWidgets.QComboBox(self.settingContent)
        self.nStage_comboBox.setMaximumSize(QtCore.QSize(202, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.nStage_comboBox.setFont(font)
        self.nStage_comboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.nStage_comboBox.setObjectName("nStage_comboBox")
        self.nStage_comboBox.addItem("")
        self.nStage_comboBox.addItem("")
        self.nStage_comboBox.addItem("")
        self.nStage_comboBox.addItem("")
        self.nStage_comboBox.addItem("")
        self.gridLayout.addWidget(self.nStage_comboBox, 16, 3, 1, 1)
        self.alloc_textCtl = QtWidgets.QLineEdit(self.settingContent)
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.alloc_textCtl.setFont(font)
        self.alloc_textCtl.setStyleSheet("")
        self.alloc_textCtl.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.alloc_textCtl.setObjectName("alloc_textCtl")
        self.gridLayout.addWidget(self.alloc_textCtl, 19, 3, 1, 1)
        self.seed_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.seed_textCtl.setEnabled(False)
        self.seed_textCtl.setMaximumSize(QtCore.QSize(202, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.seed_textCtl.setFont(font)
        self.seed_textCtl.setText("")
        self.seed_textCtl.setObjectName("seed_textCtl")
        self.gridLayout.addWidget(self.seed_textCtl, 8, 3, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem20, 39, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem21, 15, 1, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem22, 0, 1, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem23, 12, 1, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem24, 3, 1, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem25, 2, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem26, 37, 1, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem27, 22, 1, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem28, 26, 1, 1, 1)
        self.sim_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.sim_textCtl.setMaximumSize(QtCore.QSize(202, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.sim_textCtl.setFont(font)
        self.sim_textCtl.setText("")
        self.sim_textCtl.setObjectName("sim_textCtl")
        self.gridLayout.addWidget(self.sim_textCtl, 5, 3, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem29, 7, 1, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem30, 28, 1, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem31, 30, 1, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem32, 35, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.settingContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMaximumSize(QtCore.QSize(16777215, 2))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line.setFont(font)
        self.line.setStyleSheet("QWidget{\n"
"     background-color:#399ee5;\n"
"}")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(-3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 1, 1, 7)
        self.line_2 = QtWidgets.QFrame(self.settingContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 2))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("QWidget{\n"
"     background-color:#399ee5;\n"
"}")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(-3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 11, 1, 1, 7)
        spacerItem33 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem33, 21, 2, 1, 1)
        self.search_comboBox = QtWidgets.QComboBox(self.settingContent)
        self.search_comboBox.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.search_comboBox.setFont(font)
        self.search_comboBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.search_comboBox.setAcceptDrops(True)
        self.search_comboBox.setStyleSheet("QComboBox{\n"
"     max-width: 400px;\n"
"}")
        self.search_comboBox.setObjectName("search_comboBox")
        self.search_comboBox.addItem("")
        self.search_comboBox.addItem("")
        self.gridLayout.addWidget(self.search_comboBox, 36, 3, 1, 2)
        self.loadCVL_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.loadCVL_textCtl.setEnabled(False)
        self.loadCVL_textCtl.setMaximumSize(QtCore.QSize(902, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.loadCVL_textCtl.setFont(font)
        self.loadCVL_textCtl.setFocusPolicy(QtCore.Qt.NoFocus)
        self.loadCVL_textCtl.setUpdatesEnabled(True)
        self.loadCVL_textCtl.setVisible(True)
        self.loadCVL_textCtl.setWindowTitle("")
        self.loadCVL_textCtl.setWindowIconText("")
        self.loadCVL_textCtl.setWindowOpacity(1.0)
        self.loadCVL_textCtl.setWindowModified(False)
        self.loadCVL_textCtl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loadCVL_textCtl.setStyleSheet("QLineEdit:hover{\n"
"    border: 1px solid #2a4d69; \n"
"}\n"
"\n"
"QLineEdit{\n"
"    max-width: 900px;\n"
"}\n"
"")
        self.loadCVL_textCtl.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.loadCVL_textCtl.setWindowFilePath("")
        self.loadCVL_textCtl.setModified(False)
        self.loadCVL_textCtl.setReadOnly(True)
        self.loadCVL_textCtl.setObjectName("loadCVL_textCtl")
        self.gridLayout.addWidget(self.loadCVL_textCtl, 38, 3, 1, 2)
        self.loadCVL_btn = QtWidgets.QToolButton(self.settingContent)
        self.loadCVL_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.loadCVL_btn.setFont(font)
        self.loadCVL_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loadCVL_btn.setAcceptDrops(True)
        self.loadCVL_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loadCVL_btn.setStyleSheet("QToolButton{\n"
"    height: 30px;\n"
"    width: 30px;\n"
"}")
        self.loadCVL_btn.setCheckable(False)
        self.loadCVL_btn.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.loadCVL_btn.setObjectName("loadCVL_btn")
        self.gridLayout.addWidget(self.loadCVL_btn, 38, 5, 1, 1)
        self.predClinSig_checkBox = QtWidgets.QCheckBox(self.settingContent)
        self.predClinSig_checkBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predClinSig_checkBox.sizePolicy().hasHeightForWidth())
        self.predClinSig_checkBox.setSizePolicy(sizePolicy)
        self.predClinSig_checkBox.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.predClinSig_checkBox.setFont(font)
        self.predClinSig_checkBox.setChecked(False)
        self.predClinSig_checkBox.setObjectName("predClinSig_checkBox")
        self.gridLayout.addWidget(self.predClinSig_checkBox, 33, 1, 1, 3)
        self.predClinSig_textCtl = QtWidgets.QLineEdit(self.settingContent)
        self.predClinSig_textCtl.setEnabled(False)
        self.predClinSig_textCtl.setMaximumSize(QtCore.QSize(202, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segue UI Emoji")
        font.setPointSize(10)
        self.predClinSig_textCtl.setFont(font)
        self.predClinSig_textCtl.setObjectName("predClinSig_textCtl")
        self.gridLayout.addWidget(self.predClinSig_textCtl, 33, 4, 1, 1)
        self.trtEffSize_btn = QtWidgets.QPushButton(self.settingContent)
        self.trtEffSize_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.trtEffSize_btn.setFont(font)
        self.trtEffSize_btn.setObjectName("trtEffSize_btn")
        self.gridLayout.addWidget(self.trtEffSize_btn, 13, 4, 1, 1)
        self.assignPatient_btn = QtWidgets.QPushButton(self.settingContent)
        self.assignPatient_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.assignPatient_btn.setFont(font)
        self.assignPatient_btn.setObjectName("assignPatient_btn")
        self.gridLayout.addWidget(self.assignPatient_btn, 16, 4, 1, 1)
        self.trtEff_Frame = QtWidgets.QFrame(self.settingContent)
        self.trtEff_Frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.trtEff_Frame.setStyleSheet("QFrame#trtEff_Frame{\n"
"     border: 1px solid #399ee5;\n"
"     border-radius： 5px;\n"
"     border-left: 3px solid #399ee5;\n"
"}")
        self.trtEff_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trtEff_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trtEff_Frame.setObjectName("trtEff_Frame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.trtEff_Frame)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_2.setContentsMargins(20, 20, 20, 20)
        self.formLayout_2.setObjectName("formLayout_2")
        self.effSize_tableWidget = QtWidgets.QTableWidget(self.trtEff_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.effSize_tableWidget.sizePolicy().hasHeightForWidth())
        self.effSize_tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.effSize_tableWidget.setFont(font)
        self.effSize_tableWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.effSize_tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.effSize_tableWidget.setStyleSheet("QLineEdit{\n"
"    min-width: 80px;\n"
"    max-width: 1000px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}")
        self.effSize_tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.effSize_tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.effSize_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.effSize_tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.effSize_tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.effSize_tableWidget.setObjectName("effSize_tableWidget")
        self.effSize_tableWidget.setColumnCount(0)
        self.effSize_tableWidget.setRowCount(0)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.effSize_tableWidget)
        self.cancelEff_btn = QtWidgets.QToolButton(self.trtEff_Frame)
        self.cancelEff_btn.setStyleSheet("QToolButton:hover{\n"
"     background: #cce5f3;\n"
"     border: 1px solid #fafbfc;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelEff_btn.setIcon(icon)
        self.cancelEff_btn.setObjectName("cancelEff_btn")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cancelEff_btn)
        self.saveEff_btn = QtWidgets.QPushButton(self.trtEff_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.saveEff_btn.setFont(font)
        self.saveEff_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveEff_btn.setObjectName("saveEff_btn")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.saveEff_btn)
        self.resetEff_btn = QtWidgets.QPushButton(self.trtEff_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.resetEff_btn.setFont(font)
        self.resetEff_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetEff_btn.setObjectName("resetEff_btn")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.resetEff_btn)
        self.gridLayout.addWidget(self.trtEff_Frame, 14, 1, 1, 5)
        self.patNum_Frame = QtWidgets.QFrame(self.settingContent)
        self.patNum_Frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.patNum_Frame.setStyleSheet("QFrame#patNum_Frame{\n"
"     border: 1px solid #399ee5;\n"
"     border-radius： 5px;\n"
"     border-left: 3px solid #399ee5;\n"
"}")
        self.patNum_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.patNum_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.patNum_Frame.setObjectName("patNum_Frame")
        self.formLayout = QtWidgets.QFormLayout(self.patNum_Frame)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(20, 20, 20, 20)
        self.formLayout.setObjectName("formLayout")
        self.cancelPat_btn = QtWidgets.QToolButton(self.patNum_Frame)
        self.cancelPat_btn.setStyleSheet("QToolButton:hover{\n"
"     background: #cce5f3;\n"
"     border: 1px solid #fafbfc;\n"
"}\n"
"")
        self.cancelPat_btn.setIcon(icon)
        self.cancelPat_btn.setObjectName("cancelPat_btn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cancelPat_btn)
        self.patNum_tableWidget = QtWidgets.QTableWidget(self.patNum_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patNum_tableWidget.sizePolicy().hasHeightForWidth())
        self.patNum_tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.patNum_tableWidget.setFont(font)
        self.patNum_tableWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.patNum_tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.patNum_tableWidget.setStyleSheet("QLineEdit{\n"
"    min-width: 80px;\n"
"    max-width: 1000px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}\n"
"")
        self.patNum_tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.patNum_tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.patNum_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.patNum_tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.patNum_tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.patNum_tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.patNum_tableWidget.setObjectName("patNum_tableWidget")
        self.patNum_tableWidget.setColumnCount(0)
        self.patNum_tableWidget.setRowCount(0)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.patNum_tableWidget)
        self.resetPat_btn = QtWidgets.QPushButton(self.patNum_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.resetPat_btn.setFont(font)
        self.resetPat_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetPat_btn.setObjectName("resetPat_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.resetPat_btn)
        self.savePat_btn = QtWidgets.QPushButton(self.patNum_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.savePat_btn.setFont(font)
        self.savePat_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.savePat_btn.setObjectName("savePat_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.savePat_btn)
        self.gridLayout.addWidget(self.patNum_Frame, 17, 1, 1, 5)
        self.settingArea.setWidget(self.settingContent)
        self.verticalLayout.addWidget(self.settingArea)

        self.retranslateUi(MAMSWindow)
        self.nArm_comboBox.setCurrentIndex(-1)
        self.nStage_comboBox.setCurrentIndex(-1)
        self.search_comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MAMSWindow)
        MAMSWindow.setTabOrder(self.sim_textCtl, self.seed_checkBox)
        MAMSWindow.setTabOrder(self.seed_checkBox, self.seed_textCtl)
        MAMSWindow.setTabOrder(self.seed_textCtl, self.nArm_comboBox)
        MAMSWindow.setTabOrder(self.nArm_comboBox, self.trtEffSize_btn)
        MAMSWindow.setTabOrder(self.trtEffSize_btn, self.cancelEff_btn)
        MAMSWindow.setTabOrder(self.cancelEff_btn, self.effSize_tableWidget)
        MAMSWindow.setTabOrder(self.effSize_tableWidget, self.saveEff_btn)
        MAMSWindow.setTabOrder(self.saveEff_btn, self.resetEff_btn)
        MAMSWindow.setTabOrder(self.resetEff_btn, self.nStage_comboBox)
        MAMSWindow.setTabOrder(self.nStage_comboBox, self.assignPatient_btn)
        MAMSWindow.setTabOrder(self.assignPatient_btn, self.cancelPat_btn)
        MAMSWindow.setTabOrder(self.cancelPat_btn, self.patNum_tableWidget)
        MAMSWindow.setTabOrder(self.patNum_tableWidget, self.savePat_btn)
        MAMSWindow.setTabOrder(self.savePat_btn, self.resetPat_btn)
        MAMSWindow.setTabOrder(self.resetPat_btn, self.alloc_textCtl)
        MAMSWindow.setTabOrder(self.alloc_textCtl, self.fut_textCtl)
        MAMSWindow.setTabOrder(self.fut_textCtl, self.eff_textCtl)
        MAMSWindow.setTabOrder(self.eff_textCtl, self.clinSig_textCtl)
        MAMSWindow.setTabOrder(self.clinSig_textCtl, self.predict_checkBox)
        MAMSWindow.setTabOrder(self.predict_checkBox, self.predNum_textCtl)
        MAMSWindow.setTabOrder(self.predNum_textCtl, self.predSuccess_textCtl)
        MAMSWindow.setTabOrder(self.predSuccess_textCtl, self.predClinSig_checkBox)
        MAMSWindow.setTabOrder(self.predClinSig_checkBox, self.predClinSig_textCtl)
        MAMSWindow.setTabOrder(self.predClinSig_textCtl, self.loadCVL_checkBox)
        MAMSWindow.setTabOrder(self.loadCVL_checkBox, self.loadCVL_btn)

    def retranslateUi(self, MAMSWindow):
        _translate = QtCore.QCoreApplication.translate
        MAMSWindow.setWindowTitle(_translate("MAMSWindow", "Form"))
        self.label_15.setText(_translate("MAMSWindow", "Efficacy Boundary:"))
        self.eff_textCtl.setPlaceholderText(_translate("MAMSWindow", "0-1, >CF"))
        self.label_14.setText(_translate("MAMSWindow", "Futility Boundary:"))
        self.label.setText(_translate("MAMSWindow", "Simulation Setting"))
        self.label_5.setText(_translate("MAMSWindow", "Number of Simulations:"))
        self.label_2.setText(_translate("MAMSWindow", "Trial Parameters"))
        self.clinSig_textCtl.setPlaceholderText(_translate("MAMSWindow", "0-1"))
        self.predNum_Label.setText(_translate("MAMSWindow", "Number of New Patients:"))
        self.nArm_comboBox.setItemText(0, _translate("MAMSWindow", "3"))
        self.nArm_comboBox.setItemText(1, _translate("MAMSWindow", "4"))
        self.nArm_comboBox.setItemText(2, _translate("MAMSWindow", "5"))
        self.nArm_comboBox.setItemText(3, _translate("MAMSWindow", "6"))
        self.nArm_comboBox.setItemText(4, _translate("MAMSWindow", "7"))
        self.nArm_comboBox.setItemText(5, _translate("MAMSWindow", "8"))
        self.nArm_comboBox.setItemText(6, _translate("MAMSWindow", "9"))
        self.nArm_comboBox.setItemText(7, _translate("MAMSWindow", "10"))
        self.seed_checkBox.setText(_translate("MAMSWindow", "Seed:"))
        self.predSuccess_textCtl.setPlaceholderText(_translate("MAMSWindow", "0-1"))
        self.loadCVL_checkBox.setText(_translate("MAMSWindow", "Load CVL Table:"))
        self.label_12.setText(_translate("MAMSWindow", "Number of Arms:"))
        self.label_13.setText(_translate("MAMSWindow", "Number of Stages:"))
        self.label_7.setText(_translate("MAMSWindow", "Allocation Ratio (Control to Treatment):"))
        self.predict_checkBox.setText(_translate("MAMSWindow", "Predictive Probability:"))
        self.label_16.setText(_translate("MAMSWindow", "Clinically Significant Difference:"))
        self.search_Label.setText(_translate("MAMSWindow", "Method of Calculation:"))
        self.predSuccess_Label.setText(_translate("MAMSWindow", "Success Boundary:"))
        self.fut_textCtl.setPlaceholderText(_translate("MAMSWindow", "0-1"))
        self.nStage_comboBox.setItemText(0, _translate("MAMSWindow", "2"))
        self.nStage_comboBox.setItemText(1, _translate("MAMSWindow", "3"))
        self.nStage_comboBox.setItemText(2, _translate("MAMSWindow", "4"))
        self.nStage_comboBox.setItemText(3, _translate("MAMSWindow", "5"))
        self.nStage_comboBox.setItemText(4, _translate("MAMSWindow", "6"))
        self.alloc_textCtl.setPlaceholderText(_translate("MAMSWindow", "1-4"))
        self.seed_textCtl.setPlaceholderText(_translate("MAMSWindow", "0~999999"))
        self.sim_textCtl.setPlaceholderText(_translate("MAMSWindow", "1000~100000"))
        self.search_comboBox.setItemText(0, _translate("MAMSWindow", "Bisection Search"))
        self.search_comboBox.setItemText(1, _translate("MAMSWindow", "Critical Value Lookup Table"))
        self.loadCVL_btn.setText(_translate("MAMSWindow", "..."))
        self.predClinSig_checkBox.setText(_translate("MAMSWindow", "Use Same Clinically Significant Difference Or"))
        self.trtEffSize_btn.setText(_translate("MAMSWindow", "Treatment Effects"))
        self.assignPatient_btn.setText(_translate("MAMSWindow", "Assign Patients"))
        self.cancelEff_btn.setText(_translate("MAMSWindow", "..."))
        self.saveEff_btn.setText(_translate("MAMSWindow", "Save"))
        self.resetEff_btn.setText(_translate("MAMSWindow", "Reset"))
        self.cancelPat_btn.setText(_translate("MAMSWindow", "..."))
        self.resetPat_btn.setText(_translate("MAMSWindow", "Reset"))
        self.savePat_btn.setText(_translate("MAMSWindow", "Save"))

